// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/hello": {
            "post": {
                "description": "调用后端服务并返回问候语",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Hello"
                ],
                "summary": "问候接口",
                "parameters": [
                    {
                        "description": "请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_alfredchaos_demo_internal_api-gateway_dto.HelloRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功响应",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_alfredchaos_demo_internal_api-gateway_dto.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/github_com_alfredchaos_demo_internal_api-gateway_dto.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_alfredchaos_demo_internal_api-gateway_dto.HelloRequest": {
            "description": "问候请求参数",
            "type": "object"
        },
        "github_com_alfredchaos_demo_internal_api-gateway_dto.Response": {
            "description": "API 统一响应格式",
            "type": "object",
            "properties": {
                "code": {
                    "description": "错误码,0表示成功",
                    "type": "integer",
                    "example": 0
                },
                "data": {
                    "description": "响应数据",
                    "type": "string"
                },
                "message": {
                    "description": "响应消息",
                    "type": "string",
                    "example": "success"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Demo API Gateway",
	Description:      "微服务架构演示项目的 API 网关",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
